import fsp from 'node:fs/promises'
import path from 'node:path'
import { describe, expect, it } from 'vitest'
import { processSentenceSegmentation } from '../transcript'

describe('transcript', () => {
	it('processSentenceSegmentation', async () => {
		const currentDir = import.meta.dirname
		const p = path.join(currentDir, './test.json')
		const result = await fsp.readFile(p, 'utf-8')
		const data = JSON.parse(result)

		const words = data.transcription.map((item: any) => ({
			word: item.text,
			start: item.offsets.from / 1000,
			end: item.offsets.to / 1000,
		}))

		const segments = processSentenceSegmentation({ words })

		const texts = segments.map((item) => item.text)

		expect(texts).toMatchInlineSnapshot(`
			[
			  " Now China is America's biggest company,",
			  " a customer for agricultural products.",
			  " Now that President-elect Donald Trump has promised to impose steep tariffs on China,",
			  " many farmers in America's heartland fear the response from Beijing could break them.",
			  " The American Midwest has some of the most productive soil on Earth.",
			  " That's why it's often called America's breadbasket.",
			  " But in the deep of winter,",
			  " that soil gets a breather,",
			  " while farmers like Rob Schaeffer stay busy.",
			  " They're a cattle that needs to be fed.",
			  " Rob's family has been farming for five generations here in the heart of Illinois,",
			  " and a lot has changed in that time.",
			  " My dad never had to worry about a global market,",
			  " but my brother and I have to worry about a global market.",
			  " And they have reason to be concerned.",
			  " In 2018, Trump sought to punish China for unfair trade practices.",
			  " He imposed major levies on $200 billion worth of Chinese imports during his first term as president.",
			  " That pushed China,",
			  " the biggest buyer of American agricultural exports,",
			  " to implement retaliatory tariffs of their own.",
			  " The prospect of a renewed cycle of tit-for-tat tariffs in Trump's second term is reigniting those concerns.",
			  " We need China to keep buying,",
			  " and it's a huge dollar amount,",
			  " OK, for both countries.",
			  " So there's a lot of that,",
			  " there's stuff coming into us and us going to them,",
			  " and that's like we need fair trade,",
			  " OK, and equal trade so that we can move our products.",
			  " They need our products.",
			  " We want to sell them to them.",
			  " They want to buy them.",
			  " In the recent study modeling a worst-case scenario in which Chinese tariffs on U.S. goods rise by as much as 60 percent and retaliatory tariffs from other countries increase by 10 percent,",
			  " economists predicted significant export losses for the U.S. agricultural sector,",
			  " with grains seeing the biggest hit,",
			  " a few hours northwest,",
			  " this time in central Iowa.",
			  " Farmer Dave Walton is also bracing himself for what may come,",
			  " at a time where a global grain oversupply has already weighed on profits.",
			  " The ag economy is not really that good right now.",
			  " We've seen a drop in our prices.",
			  " Profitability is going to be down for next year,",
			  " get down fairly significantly,",
			  " and if we see another trade war,",
			  " we're going to go from break even to a little above to negative territory.",
			  " So that's going to be fairly devastating to us.",
			  " And Dave points out that increased tariffs on farm exports won't just impact the agricultural sector but bring knock-on effects with them.",
			  " It trickles down through the U.S. economy,",
			  " farm equipment manufacturers,",
			  " seed companies,",
			  " chemical companies,",
			  " and even the amount of money that I can spend locally with dealerships and at the restaurants and grocery stores,",
			  " that all trickles down through the economy.",
			  " The first time around,",
			  " the pain the tariff war brought upon farmers was such that the government eventually stepped in with subsidies.",
			  " But farmers here say they would take free trade over handouts any day,",
			  " and hope that this time,",
			  " the Trump government will have learned from what they view as the incoming president's past mistakes.",
			  " No, never have been.",
			  " Let's explore this with business reporter Stephen Beardsley.",
			  " Welcome Stephen,",
			  " President-elect Trump,",
			  " big fan of tariffs,",
			  " even calls himself the tariff man.",
			  " Is he listening to farmers like those we just heard from?",
			  " Yeah, Phil,",
			  " I would say that from what we've seen over the past few months,",
			  " he's even less concerned about the issue of tariffs and more willing to use them than ever.",
			  " Look at his election win, in which he often talked about tariffs.",
			  " Look at his first use of tariffs during his first term.",
			  " He got away with that pretty well, pretty unscathed.",
			  " What's interesting is that now tariffs are being talked about in a different way,",
			  " the way he's talked about them in recent months.",
			  " It's less about protecting certain industries in the U.S.,",
			  " bringing back manufacturing,",
			  " and it's more about trying to shape behavior from trading partners,",
			  " trying to bring them to the negotiating table.",
			  " It's a cudgel, in other words, that he's holding over them.",
			  " And that's why even at a time in which you do see more of an embrace of tariffs around the world to alter certain trade distortions,",
			  " there's a lot of skepticism about what Trump has proposed and how he's going to go about it.",
			  " At the end of the day, tariffs cause a short-term shock to markets.",
			  " They cause longer-term costs to rise for businesses and consumers.",
			  " And then they potentially lead to a spiral of counter tariffs,",
			  " which then affects the farmers like we saw in that piece.",
			  " And from all the evidence that we have,",
			  " there's really no way to get around that.",
			  " One has to pay the bill of these tariffs,",
			  " and countries aren't going to let their businesses be the ones who take the only hit.",
			  " Well, given all those massive downsides,",
			  " why are tariffs becoming so popular?",
			  " The world continues to change,",
			  " and I think Trump's election itself is evidence of that.",
			  " We're learning this lesson,",
			  " elite classes around the world are learning this lesson that the gains of globalization have not been as fair as they've been made out to be.",
			  " And that especially for certain sectors,",
			  " industrial sectors,",
			  " manufacturing sectors that have a special emotional resonance,",
			  " even if you can point to other sectors around the world,",
			  " around your economy,",
			  " say they've gained through globalization.",
			  " See how it actually pans out that the loss of these powerful sectors has really made a difference.",
			  " You see that in Trump's election.",
			  " That wasn't a one-off election in 2016.",
			  " He was just re-elected again.",
			  " On top of that,",
			  " you've seen the distortions recently because of China and its aggressive trade policies recently.",
			  " So you see other nations around the world also putting in tariffs.",
			  " You see the EU,",
			  " for example,",
			  " putting in tariffs against Chinese electric automobiles.",
			  " There could be more tariffs along the way against other Chinese things.",
			  " So you are seeing this kind of favorability for tariffs coming back.",
			  " The thing is, they're not the answer to everything.",
			  " And Trump wants them to be the answer to everything,",
			  " or at least that's the way he's acted in recent months.",
			  " He said that he can pay for tax cuts with them.",
			  " He can dangle them over countries' heads and they can also bring back manufacturing.",
			  " But that is disruptive when you throw them around so often.",
			  " I mean, look at Canada, Mexico.",
			  " He's trying to renege or he's proposed reneging on a free trade deal that he proposed with them.",
			  " He did with them.",
			  " So what does that say in the long run?",
			  " OK.",
			  " So do the maths for us then.",
			  " Give us all this tariff and counter tariff.",
			  " Does the US stand to gain or to lose ultimately?",
			  " I think some of the best math was there in that piece that Janelle did.",
			  " You see some of that.",
			  " They do stand to lose if there are counter tariffs.",
			  " I think the biggest loss up front is going to be on export-oriented nations such as China and such as this one,",
			  " such as Germany.",
			  " They depend on the US as a very important market.",
			  " Take Germany, for example.",
			  " The US is its single most important export destination that's only grown in recent years because China is buying less.",
			  " So what happens when it becomes more expensive to send goods over to the US?",
			  " Well, investment goes elsewhere in the world looking for where it's cheaper to get it into the US,",
			  " including into the US itself.",
			  " That's a problem.",
			  " Not only that,",
			  " if tariffs are then raised even higher for China and they can't get into the US,",
			  " where are those goods going to go?",
			  " They're going to come back right here into Europe.",
			  " And so that's another concern.",
			  " So it's not just about businesses trying to get into the US but then dealing with everything that's coming in from China.",
			  " So it just keeps going around and around and around.",
			  " These nations can raise tariffs, counter tariffs on the US.",
			  " That will bring some pain to the US as well.",
			  " And you get to this point where you say, who is winning from this?",
			  " And that's the bigger question.",
			  " OK.",
			  " The next four years is going to be such fun.",
			  " Thank you, Steven.",
			  " It's going to be interesting.",
			  " Steven Bisley from DW Business.",
			]
		`)
	})
})
